# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go Multi-Platform Build

on:
  push:
    branches: [ "main" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-os: [linux, windows, darwin]
        go-arch: [amd64, arm64]
        exclude:
          - go-os: darwin
            go-arch: amd64

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'
    
    - name: Build
      env:
        GOOS: ${{ matrix.go-os }}
        GOARCH: ${{ matrix.go-arch }}
      run: |
        OUTPUT="dist/codesnap-${{ matrix.go-arch }}-${{ matrix.go-os }}"
        if [ "${{ matrix.go-os }}" = "windows" ]; then
          OUTPUT="$OUTPUT.exe"
        fi
        go build -v -o $OUTPUT main.go
    
    - name: Test
      run: go test -v ./...
    
    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: codesnap-${{ matrix.go-arch }}-${{ matrix.go-os }}
        path: dist/codesnap-${{ matrix.go-arch }}-${{ matrix.go-os }}*
        if-no-files-found: error

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download all build artifacts
      uses: actions/download-artifact@v4
      
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          codesnap-*/codesnap-*
        draft: false
        prerelease: false
